import * as React from 'react';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import { DateTimePicker } from '@mui/lab';
import LocalizationProvider from '@mui/lab/LocalizationProvider';
import AdapterDateFns from '@mui/lab/AdapterDateFns';
import { Autocomplete, Card, CardActions, CardContent, Container, Grid, TextField, AppBar, RadioGroup, FormControlLabel, Radio, FormControl } from '@mui/material';

import { listarLocadoras, LocadoraResp } from "../hooks/locadoras/service"
import { useFormik, } from 'formik';
import { useRouter } from 'next/dist/client/router';
import Navbar from 'components/navbar';








const Home = () => {
 
return (

    <div >
      <Head>
        <title>Rent a car - Protótipo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ flexGrow: 1 }}>
        <Navbar />
      </Box>
      <LocalizationProvider dateAdapter={AdapterDateFns}>
        <Box>
          <Container>
            <Grid container>
              <Grid item xs={12}>

                <Typography variant="h3">
                  Pesquise, Compare e Alugue
                </Typography>

                <Typography variant="h4">
                  Aluguel de carros com os melhores preços
                </Typography>

              </Grid>
              <Grid item xs={12}>
                <Box sx={{marginTop: 8}} borderColor="primary.main">

                  <Card variant="outlined">
                    <CardContent>
                      <Box >
                        <Typography variant="h5">
                          Retire seu carro em:
                        </Typography>
                        </Box>
                    </CardContent>

                  </Card>

                </Box>

                <Box sx={{marginTop: 8}}  borderColor="danger">

                  <Card>
                    <CardContent>
                      <Typography variant="h4">
                        Locadoras
                      </Typography>


                    </CardContent>
                  </Card>

                </Box>

              </Grid>
            </Grid>




          </Container>
        </Box>
      </LocalizationProvider>

      <footer>

      </footer>
    </div>
  )
}

export default Home
